enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquete2/', include("enquete2.urls")),
    path('', include("main.urls")),
]

enquete/enquete2/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'enquete2'
urlpatterns = [

        path('index',views.index,name='index'),
        path('about',views.about,name='about'),
        path('contact',views.contact,name='contact'),
        path('topico/<int:topico_id>',views.topico,name='topico'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
        path('',
        views.root,
        name='root'),

        path('enquete',
        views.IndexViews.as_view(),
        name='index'),

        path('pergunta/<int:pk>',
        views.DetalhesViews.as_view(),
        name ='detalhes'),

        path('pergunta/<int:pk>/resultado',
        views.ResultadoViews.as_view(),
        name ='resultado'),

        path('pergunta/<int:id_enquete>/votacao',
        views.votacao,
        name = 'votacao'),

        path('pergunta/<int:id_categoria>/categoria',
        views.categoria,
        name = 'categoria'),


    ]

enquete/enquete2/models.py
from django.db import models
from django.utils import timezone
import datetime

class Categoria(models.Model):
    titulo = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.titulo

class Topico(models.Model):
    texto = models.CharField(max_length = 200)
    descricao = models.CharField(max_length = 500)
    data_publicacao = models.DateTimeField('Data de publicação')
    categoria = models.ManyToManyField(Categoria)
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora

class Opcao(models.Model):
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    topico = models.ForeignKey(Topico, on_delete = models.CASCADE)
    def __str__(self):
        return self.texto

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Categoria(models.Model):
    titulo = models.CharField(max_length = 200)
    descricao = models.CharField(max_length = 500)
    data_publicacao = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.titulo

class Pergunta(models.Model):
    texto = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de publicação')
    categoria = models.ManyToManyField(Categoria)
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora

class Opcao(models.Model):
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete = models.CASCADE)
    def __str__(self):
        return self.texto

enquete/enquete2/views.py
from django.shortcuts import render
from django.views import generic
from .models import Topico

def index(request):
    topico_id = Topico.objects.get(id=1)
    return render(request, 'enquete2/index.html', {'topico': topico_id})

def about(request):
    return render(request, 'enquete2/about.html', {})

def contact(request):
    return render(request, 'enquete2/contact.html', {})

def topico(request, topico_id):
    topico = Topico.objects.get(id=topico_id)
    topico_single = Topico.objects.all()
    return render(request, 'enquete2/single.html', {'topico': topico_single})

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Pergunta, Opcao, Categoria
from django.urls import reverse
from django.views import generic
from django.utils import timezone

def root(request):
    return render(request, 'main/root.html')

class IndexViews(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
        ).order_by('-data_publicacao')[:5]

class DetalhesViews(generic.DetailView):
    model = Pergunta
    template_name = 'main/detalhes.html'
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())

class ResultadoViews(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def categoria(request, id_categoria):
    context = get_object_or_404(Categoria, pk=id_categoria)
    pergunta = context.pergunta_set.all().order_by('texto')
    return render(request, 'main/categoria.html', {'categoria': context, 'pergunta':pergunta })

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta':pergunta,
            'error_message': "Selecione uma opção VÁLIDA!",
            })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(reverse('main:resultado', args=(pergunta.id,)))

enquete/enquete2/templates/enquete2/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    <meta name="description" content="150 words">
    <meta name="author" content="uipasta">
    <meta name="url" content="http://www.yourdomainname.com">
    <meta name="copyright" content="company name">
    <meta name="robots" content="index,follow">
    
    
    <title>DevBlog - Personal Blog Template</title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'enquete2/images/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon" href="{% static 'enquete2/images/favicon/apple-touch-icon.png' %}">
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/plugin.css' %}">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/style.css' %}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">

  </head>

 <body>

	
     
	 <!-- Preloader Start -->
     <div class="preloader">
	   <div class="rounder"></div>
      </div>
      <!-- Preloader End -->

    <div id="main">
        <div class="container">
            <div class="row">

                 <!-- About Me (Left Sidebar) Start -->
                 <div class="col-md-3">
                   <div class="about-fixed">
                    
                     <div class="my-pic">
                        <img src="{% static 'enquete2/images/pic/my-pic.jpeg' %}" alt="">
                        <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i class="icon-menu menu"></i></a>
                         <div id="menu" class="collapse">
                           <ul class="menu-link">
                              <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                              <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                              <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                            </ul>
                         </div>
                        </div>

                      <div class="my-detail">
                    	
                        <div class="white-spacing">
                            <h1>Guilherme Santos</h1>
                            <span>Web Developer</span>
                        </div> 
                       
                        <ul class="social-icon">
                          <li><a href="https://www.facebook.com/guilherme.pinto.35728" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a></li>
                          <li><a href="https://twitter.com/_gspgui_" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a></li>
                          <li><a href="https://www.linkedin.com/in/guilherme-pinto-89893418a/" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                          <li><a href="https://github.com/Gui-Gsp" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
                         </ul>

                    </div>
                  </div>
                </div>
                <!-- About Me (Left Sidebar) End -->

                 <!-- About Me (Right Sidebar) Start -->
                 <div class="col-md-9">
                    <div class="col-md-12 page-body">
                    	<div class="row">
                    		
                            
                            <div class="sub-title">
                           		<h2>Sobre mim</h2>
                                <a href="{% url 'enquete2:contact' %}"><i class="icon-envelope"></i></a>
                             </div>
                            
                            
                            <div class="col-md-12 content-page">
                              <div class="col-md-12 blog-post">
                            	
                                
                                <!-- My Intro Start -->
                                <div class="post-title margin-bottom-30">
                                    <h1>Oi, Eu sou o <span class="main-color">Guilherme Santos</span></h1>
                                    
                                    <ul class="knowledge">
                                      <li class="bg-color-1">Web Designer</li>
                                      <li class="bg-color-4">Web Developer</li>
                                      <li class="bg-color-6">Freelancer</li>
                                     </ul>
                                     
                                   </div>
                                   <!-- My Intro End -->
                                    
                                    
                                    <p>Meu nome é Guilherme dos Santos, eu gosto de muitas coisas e não gosto de muitas coisas também. <b>Mas uma coisa que eu não gosto, é esquecer das coisas</b>, então eu fiz essa aplicação Web para que eu possa lembrar e guardar informações aqui.</p>

                         </div>
                     
                       <!-- Footer Start -->
                       <div class="col-md-12 page-body margin-top-50 footer">
                          <footer>
                          <ul class="menu-link">
                               <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                               <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                               <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                            </ul>
                            
                          <p>© Copyright 2016 DevBlog. All rights reserved</p>
						  
						  
						  <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="http://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->
						  
                           
                         </footer>
                       </div>
                       <!-- Footer End -->
                     
                     
                  </div>
                  <!-- About Me (Right Sidebar) End -->
                
            </div>
         </div>
      </div>

    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
    
    
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{% static 'enquete2/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'enquete2/js/plugin.js' %}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{% static 'enquete2/js/scripts.js' %}"></script>

    
   </body>
 </html>

enquete/enquete2/templates/enquete2/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    <meta name="description" content="150 words">
    <meta name="author" content="uipasta">
    <meta name="url" content="http://www.yourdomainname.com">
    <meta name="copyright" content="company name">
    <meta name="robots" content="index,follow">
    
    
    <title>DevBlog - Personal Blog Template</title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'enquete2/mages/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon" href="{% static 'enquete2/images/favicon/apple-touch-icon.png' %}">
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/plugin.css' %}">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/style.css' %}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">    

  </head>

 <body>

	
     
	 <!-- Preloader Start -->
     <div class="preloader">
	   <div class="rounder"></div>
      </div>
      <!-- Preloader End -->

    <div id="main">
        <div class="container">
            <div class="row">
                 
                 <!-- About Me (Left Sidebar) Start -->
                 <div class="col-md-3">
                   <div class="about-fixed">
                    
                     <div class="my-pic">
                        <img src="{% static 'enquete2/images/pic/my-pic.jpeg' %}" alt="">
                        <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i class="icon-menu menu"></i></a>
                        <div id="menu" class="collapse">
                          <ul class="menu-link">
                            <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                            <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                            <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                          </ul>
                        </div>
                      </div>

                      <div class="my-detail">
                    	
                        <div class="white-spacing">
                            <h1>Guilherme Santos</h1>
                            <span>Web Developer</span>
                        </div> 
                       
                        <ul class="social-icon">
                          <li><a href="https://www.facebook.com/guilherme.pinto.35728" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a></li>
                          <li><a href="https://twitter.com/_gspgui_" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a></li>
                          <li><a href="https://www.linkedin.com/in/guilherme-pinto-89893418a/" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                          <li><a href="https://github.com/Gui-Gsp" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
                         </ul>

                    </div>
                  </div>
                </div>
                <!-- About Me (Left Sidebar) End -->

                 <!-- Contact (Right Sidebar) Start -->
                 <div class="col-md-9">
                    <div class="col-md-12 page-body">
                    	<div class="row">
                    		
                            
                            <div class="sub-title">
                           		<h2>Contate-me</h2>
                                <a href="{% url 'enquete2:index' %}"><i class="icon-home"></i></a>
                             </div>
                            
                            
                            <div class="col-md-12 content-page">
                              <div class="col-md-12 blog-post">
                            	
                                
                                
                                <!-- Intro Start -->
                                <div class="post-title margin-bottom-10">
                                   <h1>Querendo entrar<span class="main-color"> em contato comigo</span>?</h1>
                                   </div>
                                   
                                  <p>Só preencher esses campos aí em baixo que em pouco tempo responderei e falarei contigo.</p>
                                     <!-- Intro End -->

                               <!-- Contact Me Start -->
                               <div class="post-title margin-top-70">
                                  <h1>Contate-<span class="main-color">Me</span></h1>
                                 </div>
                                   
                                   
                                 <div class="row">
            
                                   <div class="col-md-4 col-sm-4">
                                     <div class="contact-us-detail">  
                                      <i class="icon-screen-smartphone color-6"></i>
                                      <p><a href="tel:+1234567890">+1234 567 890</a></p>
                                    </div>
                                   </div>
               
                                   <div class="col-md-4 col-sm-4">
                                     <div class="contact-us-detail">
                                      <i class="icon-envelope-open color-5"></i>
                                      <p><a href="mailto:name@domain.com">name@domain.com</a></p>
                                    </div>
                                   </div>
                 
                                   <div class="col-md-4 col-sm-4">
                                     <div class="contact-us-detail">
                                      <i class="icon-clock color-3"></i>
                                      <p>Mon - Fri 09:00 – 18:00</p>
                                    </div>
                                  </div>
              
                                </div>
            
         
                                <div class="row margin-top-30">
                                  <div class="col-md-12">   
                 
                                  <div class="row">
                                   <form>
                    
					                <div class="col-sm-6">
						              <div class="form-group">
						               <input type="text" id="name" class="form-control" placeholder="Seu nome">
						              </div>
                                     </div>
								
                                    <div class="col-sm-6">
					                  <div class="form-group">
						               <input type="email" id="email" class="form-control" placeholder="Seu email">
						              </div>
                                     </div>
                        
                                    <div class="col-sm-6">
						              <div class="form-group">
							           <input type="text" id="website" class="form-control" placeholder="Seu WebSite">
						              </div>
                                     </div>
                          
                                    <div class="col-sm-6">
						              <div class="form-group">
							           <input type="text" id="address" class="form-control" placeholder="De onde você veio?">
						              </div>
                                     </div>

                                    <div class="col-sm-12">
                                      <select id="subject" class="form-group form-control">
                                        <option value="" selected disabled>Assunto</option>
                                        <option>Quero falar coisas em geral</option>
                                        <option>Outros</option>
                                      </select>
                                    </div>
								
                                    <div class="col-sm-12">
					                  <div class="textarea-message form-group">
					                    <textarea id="message" class="textarea-message form-control" placeholder="Sua mensagem" rows="5"></textarea>
						            </div>
                                   </div>
                   
                   
                                <div class="text-center">      
		                          <button type="submit" class="load-more-button">Send</button>
	                             </div>
                       
                                 </form>
                                </div>
                              </div>
                             </div>
                             <!-- Contact Me End -->
                                
                         
                         </div>
                        </div>
                       </div>
                           
                         </div>

                       
                       <!-- Footer Start -->
                       <div class="col-md-12 page-body margin-top-50 footer">
                          <footer>
                          <ul class="menu-link">
                               <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                               <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                               <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                            </ul>
                            
                          <p>© Copyright 2016 DevBlog. All rights reserved</p>
						  
						  
						  <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="http://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->
						  
                           
                         </footer>
                       </div>
                       <!-- Footer End -->
 
                  </div>
                  <!-- Contact (Right Sidebar) End -->
                
            </div>
         </div>
      </div>

    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
  
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{% static 'enquete2/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'enquete2/js/plugin.js' %}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{% static 'enquete2/js/scripts.js' %}"></script>

   </body>
 </html>

enquete/enquete2/templates/enquete2/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    
    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- SEO -->
    <meta name="description" content="150 words">
    <meta name="author" content="uipasta">
    <meta name="url" content="http://www.yourdomainname.com">
    <meta name="copyright" content="company name">
    <meta name="robots" content="index,follow">
    
    
    <title>DevBlog - Personal Blog Template</title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'enquete2/images/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon" href="{% static 'enquete2/images/favicon/apple-touch-icon.png' %}">
    
    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/plugin.css' %}">
    
    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'enquete2/css/style.css' %}">
    
    <!-- Google Web Fonts  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">

  </head>

 <body>

	 <!-- Preloader Start -->
     <div class="preloader">
	   <div class="rounder"></div>
      </div>
      <!-- Preloader End -->

    <div id="main">
        <div class="container">
            <div class="row">

                 <!-- About Me (Left Sidebar) Start -->
                 <div class="col-md-3">
                   <div class="about-fixed">
                    
                     <div class="my-pic">
                        <img src="{% static 'enquete2/images/pic/my-pic.jpeg' %}" alt="">
                        <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i class="icon-menu menu"></i></a>
                         <div id="menu" class="collapse">
                           <ul class="menu-link">
                              <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                              <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                              <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                            </ul>
                         </div>
                        </div>

                      <div class="my-detail">
                    	
                        <div class="white-spacing">
                            <h1>Guilherme Santos</h1>
                            <span>Web Developer</span>
                        </div> 
                       
                       <ul class="social-icon">
                         <li><a href="https://www.facebook.com/guilherme.pinto.35728" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a></li>
                         <li><a href="https://twitter.com/_gspgui_" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a></li>
                         <li><a href="https://www.linkedin.com/in/guilherme-pinto-89893418a/" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                         <li><a href="https://github.com/Gui-Gsp" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
                        </ul>

                    </div>
                  </div>
                </div>
                <!-- About Me (Left Sidebar) End -->

                <!-- Blog Post (Right Sidebar) Start -->
                 <div class="col-md-9">
                    <div class="col-md-12 page-body">
                    	<div class="row">

                          <div class="sub-title">
                            <h1>NuncaEsqueça</h1>
                            <a href="{% url 'enquete2:contact' %}"><i class="icon-envelope"></i></a>
                            <h4>Minha aplicação é simplesmente colocar várias categorias de coisas que eu não quero esquecer e/ou manter
                                guardado.
                            </h4>                         			
                          </div>

                            <div class="col-md-12 content-page">

                              <!-- Blog Post Start -->
                              <div class="col-md-12 blog-post">

                                <div class="post-title">
                                  <h2>{{ topico.texto }}</h2></a>
                                </div> 

                                <div class="post-info">
                                  <span> {{ topico.data_publicacao }} por <a href="{% url 'enquete2:contact' %}" target="_blank">Guilherme Santos</a></span>
                                </div>  
                                
                                <h4>{{ topico.descricao }}</h4>                         			

                                <!-- Post List Style Start -->
                                <div class="list">
                                  <ul>
                                    {% for o in topico.opcao_set.all %}
                                      <li>{{ o.texto }}</li>
                                    {% endfor %}
                                  </ul>
                                </div>
                                <!-- Post List Style End -->

                              </div>
                              <!-- Blog Post End --> 
                              <a href="{% url 'enquete2:topico' 1 %}" class="button button-style button-anim fa fa-long-arrow-right"><span>Mais categorias</span></a>
                            </div>
                              
                      </div>
 
                    </div>

                       <!-- Footer Start -->
                       <div class="col-md-12 page-body margin-top-50 footer">
                          <footer>
                          <ul class="menu-link">
                               <li><a href="{% url 'enquete2:index' %}">Início</a></li>
                               <li><a href="{% url 'enquete2:about' %}">Sobre mim</a></li>
                               <li><a href="{% url 'enquete2:contact' %}">Contato</a></li>
                            </ul>
                            
                          <p>© Copyright 2016 DevBlog. All rights reserved</p>

						  <!-- UiPasta Credit Start -->
                          <div class="uipasta-credit">Design By <a href="http://www.uipasta.com" target="_blank">UiPasta</a></div>
                          <!-- UiPasta Credit End -->

                           
                         </footer>
                       </div>
                       <!-- Footer End -->
                     
                     
                  </div>
                  <!-- Blog Post (Right Sidebar) End -->
                
            </div>
         </div>
      </div>
    
    
    
    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    <!-- Back to Top End -->
    
    
    <!-- All Javascript Plugins  -->
    <script type="text/javascript" src="{% static 'enquete2/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'enquete2/js/plugin.js' %}"></script>
    
    <!-- Main Javascript File  -->
    <script type="text/javascript" src="{% static 'enquete2/js/scripts.js' %}"></script>

   </body>
 </html>